version: '3'

services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000" 
    restart: always

  back:
    build:
      context: ./back
    ports:
      - "3001:3001" 
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: wra4AJD.deeq
      DATABASE_NAME: jane-tonic-db
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: wra4AJD.deeq
      POSTGRES_DB: jane-tonic-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
