version: '3'
services:
  jane-tonic-db:
    image: postgres:13
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: wra4AJD.deeq
      POSTGRES_DB: jane-tonic-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - jane-tonic-network

  jane-tonic-front:
    build:
      context: ./front
      args:
        - NODE_ENV=production
    ports:
      - "5173:5173"
    env_file:
      - ./front/.env.production
    restart: always
    networks:
      - jane-tonic-network

  jane-tonic-back:
    build:
      context: ./back
    ports:
      - "5001:5001"
    depends_on:
      - jane-tonic-db
    environment:
      DATABASE_HOST: jane-tonic-db
      DATABASE_PORT: 5432
      DATABASE_USER: sa
      DATABASE_PASSWORD: wra4AJD.deeq
      DATABASE_NAME: jane-tonic-db
    restart: always
    networks:
      - jane-tonic-network

networks:
  jane-tonic-network:

volumes:
  postgres_data:
