version: '3'

services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Your_password123
    ports:
      - '5432:5432'
    networks:
      - jane_tonic_network

networks:
  jane_tonic_network:
    driver: bridge