version: '3'
services:
  jane-tonic-db:
    image: postgres:13
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: wra4AJD.deeq
      POSTGRES_DB: jane-tonic-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - jane-tonic-network

  jane-tonic-front:
    build:
      context: ./front
    ports:
      - "5173:5173"
    env_file:
      - ./front/.env
    restart: always
    networks:
      - jane-tonic-network

  jane-tonic-back:
    build:
      context: ./back
    ports:
      - "5001:5001"
    depends_on:
      - jane-tonic-db
    environment:
      DATABASE_URL: postgres://sa:wra4AJD.deeq@jane-tonic-db:5432/jane-tonic-db
      APP_PORT: 5001
      SECRETKEY: 'b^jY\"gS&2HZG-P@'
      EXPIRESIN: "1h"
      JWT_REFRESH_SECRET_KEY: "6,Z`ck7d`hdxqxQz"
    restart: always
    networks:
      - jane-tonic-network

networks:
  jane-tonic-network:

volumes:
  postgres_data: