version: '3'

services: 
    app_jane_tonic_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/app_jane_tonic:rw
      - ~/.ssh:/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5000:5000'
    networks:
      - jane_tonic_network

    db: 
      image: postgres:latest
      environment:
        POSTGRES_USER: sa
        POSTGRES_PASSWORD: Your_password123
      ports:
        - '5432:5432'
      networks:
        - jane_tonic_network

networks:
  jane_tonic_network:
    driver: bridge